import ../../src/fp,
       ./test_option,
       ./test_either,
       ./test_trym,
       ./test_list,
       ./test_map,
       ./test_function,
       ./test_stream,
       ./test_forcomp,
       ./test_forcomp_bind,
       ./test_futurem,
       ./test_mtransf,
       ./test_iterable,
       ./test_concurrent,

       ./std/test_jsonops
